name: Bump version and deploy on merge

'on':
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: version-bump
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
        with: 
          ref: main
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: 'cat package.json'
        run: cat ./package.json
      - run: ' npm ci && npm run build'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PEGA_SITE }}'
          channelId: live
          projectId: pega-site
